### ISSUE TITLE
Fix weird alignment of console/estimate on GBA_1

### ISSUE THREAD

**Issue by Vulajin** [Vulajin/rpglb19-layouts#14]
This is a possibly a little more annoying than it might seem. `gdq-runinfo` and `gdq-timer` have some kinda specific assumptions about the similar shape of their containing boxes on all of the layouts. GBA violates one of these by making the bottom blue bar very slightly larger than all the other layouts (by 2px).

My method of handling this stuff by selectively padding elements isn't quite doing it. Honestly though I think this is only for like one run so it's pretty low priority.

**Comment by Hoishin** [comment]
I think it looks good now for some reasons
