### ISSUE TITLE
Implement countdown scene per Ouro's design

### ISSUE THREAD

**Issue by Vulajin** [Vulajin/rpglb19-layouts#17]
![image](https://user-images.githubusercontent.com/5449016/56878194-a100a480-6a07-11e9-9600-ca8cb27abb03.png)

Should be pretty straightforward. Getting the now-playing info can be referenced from `rpglb-omnibar-breakinfo.ts`. The music note is just ALT+13 on your keyboard.

**Comment by Hoishin** [comment]
should be done
